### PR TITLE
Old Hungarian base Sans and Serif fonts

### PR DESCRIPTION
**Pull request by ghost**
Bug:
https://bugs.freedesktop.org/show_bug.cgi?id=107496
It implements only Sans: Regular/Bold/Bold-Oblique/Oblique and Serif:Regular/Bold/Bold-italic/Italic fonts
Mono, Light, and Condensed fonts aren't implemented, because the Old Hungarian Glyphs would be bad appereance (Mono), wrong readability (Light, Condensed)

### CODE REVIEW

**Comment by ghost** [comment]
@nocturnaldreamer 
There is a conflict between historic form of Old Hungarian letter and standard form of Old Hungarian letter.
This is the historic form:
historial_ly
This is the standard form:
standard_ly
There is a  document example:
http://mek.oszk.hu/04700/04738/04738.pdf
You will see if you find other "rovásírással" books on this page, use the historic form.
There are some city-tables:
Keszthely_rovastabla
Nagymuzsaly_rovastabla
When I developed my first Old Hungarian scripts, asked some of the Old Hungarian fan users and font developers about the letters' form - I used the strict standard form - they said, that the form letter "ely" is wrong.
My question is: may I replace standard "ely" to historic form. Old Hungarian users and text writers would be satisfied or I must to keep the standard one. The other letters form of the Old Hungarian
UNICODE standard is OK.
https://unicode.org/charts/PDF/U10C80.pdf

**Comment by hanalf** [comment]
@moyogo 
Denis!
I think, previous question of Kixidevel is maybe very important!

**Comment by ghost** [comment]
I think I must to follow the standard strictly.

**Comment by ghost** [comment]
@moyogo 
Hi, Denis.
May I ask You to write for me whether I must to generate patch or diff file, or rebuild my fork?
Thanks:
Viktor Kovács

**Comment by ghost** [comment]
@moyogo 
Hi, Denis!
Sorry, I must to close this pull request. It too large, because I did git command mistakes!
Thanks:
Viktor

**Pull request closed without merging**
