### PR TITLE
Old Hungarian patch

### PR DESCRIPTION
**Pull request by ghost**
Old Hungarian patch for Dejavu Sans fonts, and its requirements for all Dejavu fonts.
https://bugs.freedesktop.org/show_bug.cgi?id=107496

### CODE REVIEW

**Comment by hanalf** [comment]
Kixidevel!
It seems like you uploaded the full font database as a patch!
Resolve it please, then I will test for you.

**Comment by ghost** [comment]
Thanks,

I will resolve it.

Thanks for agreement for testing the patch!

Kixidevel

**Comment by ghost** [comment]
@moyogo may I ask you to accept this patch?

**Comment by ghost** [comment]
Because of a patch formatting this pull request must be closed, and the patch file must be removed. Must to be recreated the patch and new pull request opened.

**Pull request closed without merging**
