### PR TITLE
reversed comma and double low reversed-9 quotation mark

### PR DESCRIPTION
**Pull request by ghost**
This patch implements U+2e41 and U+2e42 Unicode marks, which are required for Old Hungarian script extension.
 Described in http://www.unicode.org/wg2/docs/n4268.pdf

### CODE REVIEW

**Comment by ghost** [comment]
Please merge the patch

**Comment by fitojb** [comment]
This is not the right way to patch files in Git. See https://stackoverflow.com/questions/2249852/how-to-apply-a-patch-generated-with-git-format-patch

Please amend your commit.

**Comment by HybridDog** [comment]
I think you can do it like this: 
```sh
git am -3 reversedmarks.patch && rm reversedmarks.patch && git add -A && git commit --amend
```

**Comment by ghost** [comment]
please see #25 instead

**Pull request closed without merging**
