### PR TITLE
Improve Hebrew support

### PR DESCRIPTION
**Pull request by ghost**
Improving the Hebrew support by re-basing Hebrew on Nachlieli CLM (under GPLv2 license).
Theese changes enabling Hebrew supporting in the monospaced fonts too.

The changes are tested by me, and they are good to merge.

### CODE REVIEW

**Comment by alerque** [comment]
Presumably this is related to your #361. Please actually address some of the issues brought up in discussion there.

**Comment by ghost** [comment]
> Presumably this is related to your #361. Please actually address some of the issues brought up in discussion there.

Now there are links to the related issues.

**Comment by alerque** [comment]
I already found (and linked to) the related issues. What I want is you to address the issues that have been brought up in those other discussions, especially #361.

**Comment by ghost** [comment]
Closing this PR, the Niqqud will not be fixed by re-basing on another font.

**Pull request closed without merging**
