### PR TITLE
Add UPSIDE-DOWN FACE

### PR DESCRIPTION
**Pull request by Splarv**
Add UPSIDE-DOWN FACE symbole.

### CODE REVIEW

**Comment by moyogo** [comment]
@Splarv Cool.
Can you run `make munge` and squash that into the two commits adding the glyph?
This normalizes the diff so only the added glyph data shows in the diff.

**Comment by Splarv** [comment]
Is now fine?

**Comment by moyogo** [comment]
Why did you use a flipped U+1F609 WINKING FACE instead of U+263A WHITE SMILING FACE?
A turned U+263A would be closer to the exemple glyph in the Unicode charthttp://www.unicode.org/charts/PDF/U1F600.pdf

**Comment by Splarv** [comment]
Good question. :) I worked according to Unicode standart 8.0
http://www.unicode.org/versions/Unicode8.0.0/ch22.pdf
Part 22.9 Miscellaneous Symbols, Rendering of Emoji Symbols. 
Cite: "Glyph shape: Emoji symbols may have a great deal of flexibility in the choice of
glyph shape used to render them."

Also I looked into emojipedia. http://emojipedia.org/upside-down-face/
Cite: "A face that is upside-down, representing a sense silliness or goofiness. May be implemented as..."
IMHO rolled WINKING FACE much better show  "a sense silliness or goofiness" then just WHITE SMILING FACE.

**Comment by moyogo** [comment]
OK. I'll merge this as it is. We can change it if people have an issue with it.
Thanks also .gitignore

**Pull request merged**
