### PR TITLE
Ensure list displays as list

### PR DESCRIPTION
**Pull request by ghost**
Before this commit, the list was displaying as a single, unreadable paragraph.

### CODE REVIEW

**Comment by Alhadis** [comment]
@sampablokuper This will be taken care of by #20, since I've reformatted the readme as proper Markdown. =) [Have a look](https://github.com/Cutlery-Drawer/dejavu-fonts/blob/d0922753ef756f18b62a792ca1d716375ef66441/README.md).

**Comment by sampablokuper** [comment]
@Alhadis thanks for the heads-up, and nice work on the documentation!

As for how best to handle the conflict between your and my PRs: if you're happy to remove the parts of 8b95e9ac4b7586be3fe81fa0efc71f6b15c67e03 that conflict with mine, so that both your PR and mine can be merged, that would be great.

Alternatively, if you or @moyogo could let me know if/when #20 gets merged, I will close my PR at that point.

Thanks again :)

**Comment by Alhadis** [comment]
Erm, what would be the point of merging yours if your changes are getting completely replaced by mine...?

**Comment by sampablokuper** [comment]
@Alhadis, it's not a big deal, but the answer to your question is that the purpose of merging mine as well as yours would be to:

- achieve more granular commits, giving a clearer view of which change was submitted when and by whom; and
- thereby give credit where credit is due, as my PR was submitted more than a month prior to yours, and should reasonably receive priority.

Hope that seems fair :)

**Comment by Alhadis** [comment]
Point #2 sounds like your real motive, because point #1 is adding nothing but noise to this repository's revision history.

If I were the maintainer, I'd logically close whatever pull-requests were logically superseded by another that was accepted. Furthermore, you should know open-source is a thankless job... the reward should be in the contribution itself, not with racking up credits.

Also, uh, you haven't exactly added much that's worth including in a revision history... it's literally just a formatting fix... and a decidedly trivial one at that...

**Comment by sampablokuper** [comment]
@Alhadis, no sleep being lost; maybe I'm just more of a FIFO than a LIFO sort of person, when it comes to PRs :) And yes, agreed, it's up to the maintainer. Thanks again for doing so much work on #20 and for the heads-up! 👍

**Comment by moyogo** [comment]
@sampablokuper Sorry for not merging you PR earlier. I merged #20.

**Pull request closed without merging**
