### PR TITLE
Fix Hebrew Shin and Sin dots

### PR DESCRIPTION
**Pull request by ghost**
Fixes שׁ and שׂ.

### CODE REVIEW

**Comment by alerque** [comment]
The fact that the diff is too large for GitHub to show suggests to me you've done something wrong here. Diffing an SFD file where only a couple of source glyphs have been changed should only be a couple dozen lines of code changes. Why this PR entirely deletes some SFD sources files is also a mystery. I think you'll need these issues addressed before it can be properly reviewed.

**Comment by alerque** [comment]
...and now you've **added** TTF files. Please don't do that, just edit the existing SFD sources with *just* the changes relevant to this PR.

**Comment by ghost** [comment]
I am sorry for this, now the .sfd file is uploaded. What are the changed source glyphs?

**Comment by alerque** [comment]
Your PR says:

> Fixes שׁ and שׂ.

That's something or other you did to two glyphs.

The GitHub PR code review says:

> 48,310 additions, 34,590 deletions not shown because the diff is too large.

That doesn't compute. Each glyph section in an SFD file is somewhere between 5 and a couple dozen lines depending on complexity. Anything you did should be small enough to show a diff for. Whatever umpteen thousand lines you changed probably means you did something to *every* glyph in the the font, something you probably don't want to do — and will surely delay or block your actual fixes being merged.

**Comment by alerque** [comment]
For comparison check out what the "filed changed" tab of a good PR looks like on a font I maintain: https://github.com/alerque/libertinus/pull/398/files

Note that each SFD file changed only has a handful of changed lines. It was quite easy to see what the PR changed and confirm that it didn't break anything else. Such is not the case for this one.

**Comment by ghost** [comment]
The source glyphs are linked to the Sin and Shin dots that should be moved. I will try to move the Sin and Shin dots without changing the source glyphs.

**Comment by omeritzics** [comment]
> The source glyphs are linked to the Sin and Shin dots that should be moved. I will try to move the Sin and Shin dots without changing the source glyphs.

This is not the problem, now I know the real problem and will fix it.

**Comment by ghost** [comment]
At the moment, fixing שׁ and שׂ dots require changing an source glyph.

**Comment by ghost** [comment]
This PR will be in draft mode until the diff will be enough small.

**Comment by ghost** [comment]
Currently, SIn and Shin dot cannot be fixed without a big diff, so this PR will be closed and the fixes for Sin and Shin dots will be later.

**Pull request closed without merging**
